include: package:lints/recommended.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
  errors:
    # Treat missing returns as errors.
    missing_return: error

linter:
  rules:
    # Style
    - prefer_single_quotes
    - always_declare_return_types
    - annotate_overrides
    - avoid_empty_else
    - avoid_relative_lib_imports
    - avoid_returning_null_for_void
    - avoid_shadowing_type_parameters
    - avoid_types_as_parameter_names
    - camel_case_extensions
    - camel_case_types
    - curly_braces_in_flow_control_structures
    - file_names
    - flutter_style_todos
    - library_names
    - library_prefixes
    - non_constant_identifier_names
    - null_closures
    - omit_local_variable_types
    - prefer_adjacent_string_concatenation
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_contains
    - prefer_final_fields
    - prefer_generic_function_type_aliases
    - prefer_if_null_operators
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_null_aware_operators
    - prefer_spread_collections
    - recursive_getters
    - slash_for_doc_comments
    - type_init_formals
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_new
    - unnecessary_null_in_if_null_operators
    - unnecessary_this
    - unrelated_type_equality_checks
    - use_function_type_syntax_for_parameters
    - use_rethrow_when_possible
    - valid_regexps
